### ISSUE TITLE
Error while installation on Windows 8, Python 2.7

### ISSUE THREAD

**Issue by Jeet1994** [cyberdelia/flask-mysql#18]
I have tried to install flask-mysql both by **`pip`** and by downloading the github repo and then doing **`python setup.py install`**.
Both the time I get the error as follows:
```
gcc.exe: error: /Zl: No such file or directory
error: Setup script exited with error: command 'G:\\Packaged_Software_bundles\\WinPython-64bit-2.7.10.3\\python-2.7.10.amd64\\Scripts\\gcc.exe' failed
 with exit status 1
```

**Comment by cyberdelia** [comment]
You might get some luck with new version that uses pysmysql.
Looks like a compilation problem from mysqldb.
