### ISSUE TITLE
flaskext

### ISSUE THREAD

**Issue by ravinata** [cyberdelia/flask-mysql#22]
/usr/lib64/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.mysql is deprecated, use flask_mysql instead.
  .format(x=modname), ExtDeprecationWarning

I am using Python 2.7.5

I installed flask-mysql and so on... I already have a few database stored proc working and using in my .py files.....  All this works on my RPI 3. but, now, I am deploying the application to the Centos 7 and Apache Server 2.4. 

the /var/log/httpd/error_log says:
[Mon Nov 14 10:55:37.688313 2016] [:error] [pid 23145]   .format(x=modname), ExtDeprecationWarning
[Mon Nov 14 10:55:37.696461 2016] [:error] [pid 23145] /usr/lib64/python2.7/site-packages/flask/exthook.py:106: ExtDeprecationWarning: Detected extension named flaskext.mysql, please rename it to flask_mysql. The old form is deprecated.
[Mon Nov 14 10:55:37.696477 2016] [:error] [pid 23145]   .format(x=modname), ExtDeprecationWarning

current situation:

my apache server is running. but, error. 

[root@localhost httpd]# curl http://localhost
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

in my wsgi file (in /var/www/html/myapplication  folder,  I have a myapplication.wsgi)

**Comment by ravinata** [comment]
I have no luck in getting the wsgi working. All my .py works well but,  not able to deploy to Apache 2. (I am using Flask, MySql.
I have the wsgi file  and also the app.conf  file in the /etc/httpd/conf.d  folder.

**Comment by Regner** [comment]
How are you doing the import of flask-mysql in your code?

**Comment by themattmane** [comment]
I am facing the same issue. I have installed the flask-mysql through pip in my code.

" from flaskext.mysql import MySQL " - in .py file

" sudo pip install flask-mysql " - installed on command line

The code runs fine on my local server but facing issues when trying to deploy the application to pythonanywhere.com.  

@Regner

**Comment by drakerehfeld** [comment]
bump on this -- anyone know a workaround?

**Comment by GeneralTyres** [comment]
At the present I am importing like this:

`from flaskext.mysql import MySQL`

But I have had some problems with it in the past. Don't actually know why it's working at the moment.

**Comment by ratanparmar** [comment]
I tried installing from 
pip3 install flask-mysql for python version >3
it worked for me!!
