### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by sparkxxf** [cyberdelia/flask-mysql#3]
Please give a docs to explain how to use this. Even it is just so easy to you.Thank you!

**Comment by s2t2** [comment]
thanks for this library, would you be able to share an example of how to use this library to perform an `INSERT INTO` query? I've been trying a few interpolation methods, but right now I'm running into quoting issues...

**Comment by s2t2** [comment]
i'd like to confirm there is no need to close connections when using this library?
