### ISSUE TITLE
Can I use flask-mysql for secure connection over ssl? 

### ISSUE THREAD

**Issue by nikolamilosevic86** [cyberdelia/flask-mysql#34]
At the moment, I don't see any configuration variable that would allow me to add certificate. On my flask app I am getting error pymysql.err.InternalError: (3159, 'Connections using insecure transport are prohibited while --require_secure_transport=ON.') if I am forcing secure connections to the database. Can you please add using secure connections to the library?

**Comment by jhodges10** [comment]
Any thoughts on this @cyberdelia ?

**Comment by cyberdelia** [comment]
I’m open to it, I’ll welcome a PR. I should also move this repo to @jazzband.
