### ISSUE TITLE
How replace mysql.connection.commit in this version?

### ISSUE THREAD

**Issue by Salchi12** [cyberdelia/flask-mysql#43]
i try to do a proyect but.....pum!!! this the error that always appear 

AttributeError

AttributeError: 'function' object has no attribute 'commit'

if anybody know the solucion please tell me

**Comment by AlbertoCrespoGuzman** [comment]
sam here

**Comment by luisjimenez6245** [comment]
can you pls upload  more info? Try to include the error traceback.

**Comment by lukahorvat96** [comment]
same here

**Comment by lukahorvat96** [comment]
I found out the solution "**mydb.get_db().commit()**".

Example:
```
app.config['MYSQL_DATABASE_HOST'] = 'localhost'
app.config['MYSQL_DATABASE_USER'] = 'root'
app.config['MYSQL_DATABASE_PASSWORD'] = ''
app.config['MYSQL_DATABASE_DB'] = 'db'
 
mydb = MySQL(app)
mydb.init_app(app)
mycursor = mydb.get_db().cursor()
mycursor.execute(query, values)
mydb.get_db().commit()
```
