### ISSUE TITLE
Borken style in "Multiple connection example" section

### ISSUE THREAD

**Issue by DevDengChao** [cyberdelia/flask-mysql#53]
![image](https://user-images.githubusercontent.com/16363180/147310174-084ec566-18fc-4b62-9bb2-748c288f0367.png)

See https://flask-mysql.readthedocs.io/en/stable/#usage

**Comment by cyberdelia** [comment]
It's fixed in [latest](https://flask-mysql.readthedocs.io/en/latest/).
