### ISSUE TITLE
Documentation possibly needs formatting

### ISSUE THREAD

**Issue by jdeisenberg** [cyberdelia/flask-mysql#56]
The “Multiple Connections Example” in the “Usage” section at https://flask-mysql.readthedocs.io/en/stable/ should be indented so that line breaks are preserved. (See attached screenshot)
![flask_mysql_usage](https://github.com/cyberdelia/flask-mysql/assets/160096/c4fbb956-fe28-43f7-8fba-d8b0a7cebd5f)

**Comment by cyberdelia** [comment]
See #53
