### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by sseide** [cyberdelia/flask-mysql#8]
flask-mysql depends on  MySQL-python package that does not work with python 3.

Is it possible to switch dependency from mysql-python to other database driver like PyMySQL with full python 3 support?

**Comment by AmaxJ** [comment]
second this

**Comment by toddjcrane** [comment]
+1

**Comment by jawatson** [comment]
+1

**Comment by cyberdelia** [comment]
PR are welcome.

**Comment by corinnab** [comment]
+1
