### ISSUE TITLE
added support for multiple database connections, also cursorclass, and autcommit options...

### ISSUE THREAD

**Issue by coinmx** [cyberdelia/flask-mysql#9]
<pre>
# -*- coding: UTF-8 -*-
from __future__ import absolute_import
import MySQLdb

from flask import _request_ctx_stack

"""
from flask.ext import MySQL
from MySQLdb.cursors import DictCursor
from flask import Flask

app = Flask(__name__)
sql = MySQL(autocommit = True, cursorclass = DictCursor)
sql.init_app(app)

@app.route('/')
def index():
    cur = sql.get_db().cursor()
    cur.execute('select now() as timenow')
    res = fetchone()
    return "time now: " + res['timenow']
"""

class MySQL(object):
    def __init__(self, app=None, prefix='MYSQL', autocommit = Flase, cursorclass = None):
        self.prefix = prefix
        self.autocommit = autocommit
        self.cursorclass = cursorclass
        if app is not None:
            self.app = app
            self.init_app(self.app)
        else:
            self.app = None

    def init_app(self, app):
        self.app = app
        self.app.config.setdefault(self.prefix + '_DATABASE_HOST', 'localhost')
        self.app.config.setdefault(self.prefix + '_DATABASE_PORT', 3306)
        self.app.config.setdefault(self.prefix + '_DATABASE_USER', None)
        self.app.config.setdefault(self.prefix + '_DATABASE_PASSWORD', None)
        self.app.config.setdefault(self.prefix + '_DATABASE_DB', None)
        self.app.config.setdefault(self.prefix + '_DATABASE_CHARSET', 'utf8')
        self.app.config.setdefault(self.prefix + '_DATABASE_USE_UNICODE', True)
        self.app.teardown_request(self.teardown_request)
        self.app.before_request(self.before_request)

    def connect(self):
        kwargs = {}
        if self.app.config[self.prefix + '_DATABASE_HOST']:
            kwargs['host'] = self.app.config[self.prefix + '_DATABASE_HOST']
        if self.app.config[self.prefix + '_DATABASE_PORT']:
            kwargs['port'] = self.app.config[self.prefix + '_DATABASE_PORT']
        if self.app.config[self.prefix + '_DATABASE_USER']:
            kwargs['user'] = self.app.config[self.prefix + '_DATABASE_USER']
        if self.app.config[self.prefix + '_DATABASE_PASSWORD']:
            kwargs['passwd'] = self.app.config[self.prefix + '_DATABASE_PASSWORD']
        if self.app.config[self.prefix + '_DATABASE_DB']:
            kwargs['db'] = self.app.config[self.prefix + '_DATABASE_DB']
        if self.app.config[self.prefix + '_DATABASE_CHARSET']:
            kwargs['charset'] = self.app.config[self.prefix + '_DATABASE_CHARSET']
        if self.app.config[self.prefix + '_DATABASE_USE_UNICODE']:
            kwargs['use_unicode'] = self.app.config[self.prefix + '_DATABASE_USE_UNICODE']
        if self.cursorclass:
            kwargs['cursorclass'] = self.cursorclass
        db = MySQLdb.connect(**kwargs)
        db.autocommit(self.autocommit)
        return db

    def before_request(self):
        ctx = _request_ctx_stack.top
        if hasattr(ctx, 'mysql_cons'):
            ctx.mysql_cons[self.prefix] = self.connect()
        else:
            ctx.mysql_cons = {self.prefix : self.connect()}
    
    def teardown_request(self, exception):
        ctx = _request_ctx_stack.top
        if hasattr(ctx, 'mysql_cons'):
            ctx.mysql_cons[self.prefix].close()

    def get_db(self):
        ctx = _request_ctx_stack.top
        if ctx is not None:
            return ctx.mysql_cons[self.prefix]

</pre>

**Comment by Regner** [comment]
Would love to see the cursorclass make it into the master.

**Comment by ivandigiusto** [comment]
@Regner - #7 has added ability to pass cursorclass and other parameters to MySQLdb.connect().  This issue can be closed.

**Comment by pl4g4** [comment]
How would u pass the parameters 'cursorclass' to have 'MySQLdb.cursors.DictCursor'

**Comment by ivandigiusto** [comment]
It's right at the top of this page:
```
from flask.ext import MySQL
from MySQLdb.cursors import DictCursor
from flask import Flask

app = Flask(__name__)
sql = MySQL(autocommit = True, cursorclass = DictCursor)
sql.init_app(app)
```

**Comment by pl4g4** [comment]
But this 

```
class MySQL(object):
    def __init__(self, app=None, prefix='MYSQL', autocommit = Flase, cursorclass = None):
```

doesnt look like its in the source code. check #7

**Comment by ivandigiusto** [comment]
I am posting this to help others who don't realize that they can autocommit and cursorclass with this library.

The following code makes sure that your autocommit and cursorclass choices are passed through when the connection is made.

    class MySQL(object):
        def __init__(self, app=None, **connect_args):
            self.connect_args = connect_args

Just use the following code and you will have both autocommit and cursorclass.

from flask import Flask
from flaskext.mysql import MySQL
from pymysql.cursors import DictCursor

app = Flask(__name__)
sql = MySQL(autocommit = True, cursorclass = DictCursor)
app.config['MYSQL_DATABASE_USER'] = 'myusername'
app.config['MYSQL_DATABASE_PASSWORD'] = 'mysecurepassword'
app.config['MYSQL_DATABASE_DB'] = 'mydb'
app.config['MYSQL_DATABASE_HOST'] = 'mydbserver.com'
sql.init_app(app)
